-- Bitacoras v1 schema
-- Fecha: 2026-06-24
-- Alcance: captura digital para ECEXTT, ECINT y VOLADORES por servicio
begin;
-- 1) Enums
create type public.bitacora_tipo as enum ('ECEXTT', 'ECINT', 'VOLADORES');
create type public.bitacora_estado as enum ('borrador', 'activa', 'archivada');
create type public.revision_estado as enum ('en_captura', 'parcial', 'cerrada');
create type public.revision_estacion_estado as enum (
    'revisada',
    'no_revisada',
    'sin_bitacora_disponible'
);
-- 2) Bitacoras por direccion/tipo/version
create table public."Bitacoras" (
    id bigint generated by default as identity primary key,
    organizacion text not null,
    cliente_id bigint not null references public."Clientes" (id),
    direccion_id bigint not null references public."Direcciones" (id),
    tipo public.bitacora_tipo not null,
    nombre text,
    version integer not null default 1,
    estado public.bitacora_estado not null default 'activa',
    layout_image_url text,
    layout_width integer,
    layout_height integer,
    notas_generales text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (organizacion, direccion_id, tipo, version)
);
create unique index "Bitacoras_una_activa_por_direccion_tipo" on public."Bitacoras" (organizacion, direccion_id, tipo)
where estado = 'activa';
-- 3) Estaciones de la bitacora
create table public."EstacionesBitacora" (
    id bigint generated by default as identity primary key,
    bitacora_id bigint not null references public."Bitacoras" (id) on delete cascade,
    organizacion text not null,
    codigo_estacion text not null,
    orden integer,
    area text,
    zona text,
    descripcion text,
    activa boolean not null default true,
    x_percent numeric(5, 2),
    y_percent numeric(5, 2),
    metadata_json jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (bitacora_id, codigo_estacion),
    check (codigo_estacion ~ '^(EXT|INT|VOL)-[0-9]{2,3}$')
);
create index "EstacionesBitacora_idx_bitacora" on public."EstacionesBitacora" (bitacora_id);
create index "EstacionesBitacora_idx_org" on public."EstacionesBitacora" (organizacion);
-- 4) Catalogo de claves por organizacion
create table public."ClavesBitacora" (
    id bigint generated by default as identity primary key,
    organizacion text not null,
    tipo public.bitacora_tipo,
    clave text not null,
    titulo text not null,
    concepto text not null,
    activo boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (organizacion, tipo, clave)
);
create index "ClavesBitacora_idx_org_tipo" on public."ClavesBitacora" (organizacion, tipo);
-- 5) Revision por servicio (cabecera)
create table public."RevisionesBitacora" (
    id bigint generated by default as identity primary key,
    bitacora_id bigint references public."Bitacoras" (id),
    servicio_id bigint not null references public."Servicios" (id) on delete cascade,
    direccion_id bigint not null references public."Direcciones" (id),
    tecnico_id bigint references public."Empleados" (id),
    estado public.revision_estado not null default 'en_captura',
    no_hay_bitacora_disponible boolean not null default false,
    folio integer,
    fecha_servicio date,
    hora_entrada text,
    hora_salida text,
    encargado text,
    encargado_info text,
    observacion_general text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (servicio_id, bitacora_id)
);
create index "RevisionesBitacora_idx_servicio" on public."RevisionesBitacora" (servicio_id);
create index "RevisionesBitacora_idx_direccion" on public."RevisionesBitacora" (direccion_id);
-- 6) Captura por estacion en una revision
create table public."RevisionEstacionesBitacora" (
    id bigint generated by default as identity primary key,
    revision_id bigint not null references public."RevisionesBitacora" (id) on delete cascade,
    estacion_id bigint references public."EstacionesBitacora" (id) on delete
    set null,
        revisada boolean not null default false,
        estado public.revision_estacion_estado not null default 'no_revisada',
        consumo_porcentaje smallint,
        goma_cambiada boolean,
        observacion text,
        created_at timestamptz not null default now(),
        updated_at timestamptz not null default now(),
        unique (revision_id, estacion_id),
        check (
            consumo_porcentaje is null
            or consumo_porcentaje in (0, 25, 50, 75, 100)
        )
);
create index "RevisionEstaciones_idx_revision" on public."RevisionEstacionesBitacora" (revision_id);
create index "RevisionEstaciones_idx_estacion" on public."RevisionEstacionesBitacora" (estacion_id);
-- 7) Hallazgos por plaga (interior/voladores y casos exteriores)
create table public."HallazgosBitacora" (
    id bigint generated by default as identity primary key,
    revision_estacion_id bigint not null references public."RevisionEstacionesBitacora" (id) on delete cascade,
    plaga_id bigint references public."Plagas" (id),
    cantidad integer not null default 0,
    comentario text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    check (cantidad >= 0)
);
create index "HallazgosBitacora_idx_revision_estacion" on public."HallazgosBitacora" (revision_estacion_id);
create index "HallazgosBitacora_idx_plaga" on public."HallazgosBitacora" (plaga_id);
-- 8) Multiples claves por estacion y revision
create table public."RevisionEstacionesClaves" (
    id bigint generated by default as identity primary key,
    revision_estacion_id bigint not null references public."RevisionEstacionesBitacora" (id) on delete cascade,
    clave_id bigint not null references public."ClavesBitacora" (id),
    created_at timestamptz not null default now(),
    unique (revision_estacion_id, clave_id)
);
create index "RevisionEstacionesClaves_idx_revision_estacion" on public."RevisionEstacionesClaves" (revision_estacion_id);
create index "RevisionEstacionesClaves_idx_clave" on public."RevisionEstacionesClaves" (clave_id);
-- 9) Vista util para listado rapido por servicio
create view public."vw_bitacora_servicio_estado" with (security_invoker = true) as
select s.id as servicio_id,
    s.folio,
    s.fecha_servicio,
    s.direccion_id,
    b.id as bitacora_id,
    b.tipo as tipo_bitacora,
    rb.id as revision_id,
    rb.estado as estado_revision,
    rb.no_hay_bitacora_disponible
from public."Servicios" s
    left join public."Bitacoras" b on b.direccion_id = s.direccion_id
    and b.organizacion = s.organizacion
    and b.estado = 'activa'
    left join public."RevisionesBitacora" rb on rb.servicio_id = s.id
    and rb.bitacora_id = b.id;
-- 10) Helpers de seguridad para RLS
create or replace function public.user_belongs_to_org(_organizacion text) returns boolean language sql stable security definer
set search_path = public as $$
select exists (
        select 1
        from public."Empleados" e
        where e.user_id = auth.uid()
            and e.organizacion = _organizacion
            and coalesce(e.activo, true) = true
    );
$$;
create or replace function public.user_is_org_admin(_organizacion text) returns boolean language sql stable security definer
set search_path = public as $$
select exists (
        select 1
        from public."Empleados" e
        where e.user_id = auth.uid()
            and e.organizacion = _organizacion
            and coalesce(e.activo, true) = true
            and e.tipo_rol in ('administrador', 'superadmin')
    );
$$;
-- 11) RLS
alter table public."Bitacoras" enable row level security;
alter table public."EstacionesBitacora" enable row level security;
alter table public."ClavesBitacora" enable row level security;
alter table public."RevisionesBitacora" enable row level security;
alter table public."RevisionEstacionesBitacora" enable row level security;
alter table public."HallazgosBitacora" enable row level security;
alter table public."RevisionEstacionesClaves" enable row level security;
alter table public."Bitacoras" force row level security;
alter table public."EstacionesBitacora" force row level security;
alter table public."ClavesBitacora" force row level security;
alter table public."RevisionesBitacora" force row level security;
alter table public."RevisionEstacionesBitacora" force row level security;
alter table public."HallazgosBitacora" force row level security;
alter table public."RevisionEstacionesClaves" force row level security;
-- Bitacoras: lectura por organizacion, escritura solo admin
create policy "Bitacoras_select_org" on public."Bitacoras" for
select to authenticated using (public.user_belongs_to_org(organizacion));
create policy "Bitacoras_insert_admin" on public."Bitacoras" for
insert to authenticated with check (public.user_is_org_admin(organizacion));
create policy "Bitacoras_update_admin" on public."Bitacoras" for
update to authenticated using (public.user_is_org_admin(organizacion)) with check (public.user_is_org_admin(organizacion));
create policy "Bitacoras_delete_admin" on public."Bitacoras" for delete to authenticated using (public.user_is_org_admin(organizacion));
-- Estaciones: lectura por organizacion, escritura solo admin
create policy "EstacionesBitacora_select_org" on public."EstacionesBitacora" for
select to authenticated using (public.user_belongs_to_org(organizacion));
create policy "EstacionesBitacora_insert_admin" on public."EstacionesBitacora" for
insert to authenticated with check (public.user_is_org_admin(organizacion));
create policy "EstacionesBitacora_update_admin" on public."EstacionesBitacora" for
update to authenticated using (public.user_is_org_admin(organizacion)) with check (public.user_is_org_admin(organizacion));
create policy "EstacionesBitacora_delete_admin" on public."EstacionesBitacora" for delete to authenticated using (public.user_is_org_admin(organizacion));
-- Claves: lectura por organizacion, escritura solo admin
create policy "ClavesBitacora_select_org" on public."ClavesBitacora" for
select to authenticated using (public.user_belongs_to_org(organizacion));
create policy "ClavesBitacora_insert_admin" on public."ClavesBitacora" for
insert to authenticated with check (public.user_is_org_admin(organizacion));
create policy "ClavesBitacora_update_admin" on public."ClavesBitacora" for
update to authenticated using (public.user_is_org_admin(organizacion)) with check (public.user_is_org_admin(organizacion));
create policy "ClavesBitacora_delete_admin" on public."ClavesBitacora" for delete to authenticated using (public.user_is_org_admin(organizacion));
-- Revisiones: tecnicos/admin de la misma organizacion
create policy "RevisionesBitacora_select_org" on public."RevisionesBitacora" for
select to authenticated using (
        exists (
            select 1
            from public."Servicios" s
            where s.id = servicio_id
                and public.user_belongs_to_org(s.organizacion)
        )
    );
create policy "RevisionesBitacora_insert_org" on public."RevisionesBitacora" for
insert to authenticated with check (
        exists (
            select 1
            from public."Servicios" s
            where s.id = servicio_id
                and public.user_belongs_to_org(s.organizacion)
        )
    );
create policy "RevisionesBitacora_update_org" on public."RevisionesBitacora" for
update to authenticated using (
        exists (
            select 1
            from public."Servicios" s
            where s.id = servicio_id
                and public.user_belongs_to_org(s.organizacion)
        )
    ) with check (
        exists (
            select 1
            from public."Servicios" s
            where s.id = servicio_id
                and public.user_belongs_to_org(s.organizacion)
        )
    );
create policy "RevisionesBitacora_delete_org" on public."RevisionesBitacora" for delete to authenticated using (
    exists (
        select 1
        from public."Servicios" s
        where s.id = servicio_id
            and public.user_is_org_admin(s.organizacion)
    )
);
-- RevisionEstaciones: tecnicos/admin de la misma organizacion
create policy "RevisionEstaciones_select_org" on public."RevisionEstacionesBitacora" for
select to authenticated using (
        exists (
            select 1
            from public."RevisionesBitacora" rb
                join public."Servicios" s on s.id = rb.servicio_id
            where rb.id = revision_id
                and public.user_belongs_to_org(s.organizacion)
        )
    );
create policy "RevisionEstaciones_insert_org" on public."RevisionEstacionesBitacora" for
insert to authenticated with check (
        exists (
            select 1
            from public."RevisionesBitacora" rb
                join public."Servicios" s on s.id = rb.servicio_id
            where rb.id = revision_id
                and public.user_belongs_to_org(s.organizacion)
        )
    );
create policy "RevisionEstaciones_update_org" on public."RevisionEstacionesBitacora" for
update to authenticated using (
        exists (
            select 1
            from public."RevisionesBitacora" rb
                join public."Servicios" s on s.id = rb.servicio_id
            where rb.id = revision_id
                and public.user_belongs_to_org(s.organizacion)
        )
    ) with check (
        exists (
            select 1
            from public."RevisionesBitacora" rb
                join public."Servicios" s on s.id = rb.servicio_id
            where rb.id = revision_id
                and public.user_belongs_to_org(s.organizacion)
        )
    );
create policy "RevisionEstaciones_delete_org" on public."RevisionEstacionesBitacora" for delete to authenticated using (
    exists (
        select 1
        from public."RevisionesBitacora" rb
            join public."Servicios" s on s.id = rb.servicio_id
        where rb.id = revision_id
            and public.user_is_org_admin(s.organizacion)
    )
);
-- Hallazgos: tecnicos/admin de la misma organizacion
create policy "Hallazgos_select_org" on public."HallazgosBitacora" for
select to authenticated using (
        exists (
            select 1
            from public."RevisionEstacionesBitacora" reb
                join public."RevisionesBitacora" rb on rb.id = reb.revision_id
                join public."Servicios" s on s.id = rb.servicio_id
            where reb.id = revision_estacion_id
                and public.user_belongs_to_org(s.organizacion)
        )
    );
create policy "Hallazgos_insert_org" on public."HallazgosBitacora" for
insert to authenticated with check (
        exists (
            select 1
            from public."RevisionEstacionesBitacora" reb
                join public."RevisionesBitacora" rb on rb.id = reb.revision_id
                join public."Servicios" s on s.id = rb.servicio_id
            where reb.id = revision_estacion_id
                and public.user_belongs_to_org(s.organizacion)
        )
    );
create policy "Hallazgos_update_org" on public."HallazgosBitacora" for
update to authenticated using (
        exists (
            select 1
            from public."RevisionEstacionesBitacora" reb
                join public."RevisionesBitacora" rb on rb.id = reb.revision_id
                join public."Servicios" s on s.id = rb.servicio_id
            where reb.id = revision_estacion_id
                and public.user_belongs_to_org(s.organizacion)
        )
    ) with check (
        exists (
            select 1
            from public."RevisionEstacionesBitacora" reb
                join public."RevisionesBitacora" rb on rb.id = reb.revision_id
                join public."Servicios" s on s.id = rb.servicio_id
            where reb.id = revision_estacion_id
                and public.user_belongs_to_org(s.organizacion)
        )
    );
create policy "Hallazgos_delete_org" on public."HallazgosBitacora" for delete to authenticated using (
    exists (
        select 1
        from public."RevisionEstacionesBitacora" reb
            join public."RevisionesBitacora" rb on rb.id = reb.revision_id
            join public."Servicios" s on s.id = rb.servicio_id
        where reb.id = revision_estacion_id
            and public.user_is_org_admin(s.organizacion)
    )
);
-- RevisionEstacionesClaves: tecnicos/admin de la misma organizacion
create policy "RevisionEstacionesClaves_select_org" on public."RevisionEstacionesClaves" for
select to authenticated using (
        exists (
            select 1
            from public."RevisionEstacionesBitacora" reb
                join public."RevisionesBitacora" rb on rb.id = reb.revision_id
                join public."Servicios" s on s.id = rb.servicio_id
            where reb.id = revision_estacion_id
                and public.user_belongs_to_org(s.organizacion)
        )
    );
create policy "RevisionEstacionesClaves_insert_org" on public."RevisionEstacionesClaves" for
insert to authenticated with check (
        exists (
            select 1
            from public."RevisionEstacionesBitacora" reb
                join public."RevisionesBitacora" rb on rb.id = reb.revision_id
                join public."Servicios" s on s.id = rb.servicio_id
            where reb.id = revision_estacion_id
                and public.user_belongs_to_org(s.organizacion)
        )
    );
create policy "RevisionEstacionesClaves_delete_org" on public."RevisionEstacionesClaves" for delete to authenticated using (
    exists (
        select 1
        from public."RevisionEstacionesBitacora" reb
            join public."RevisionesBitacora" rb on rb.id = reb.revision_id
            join public."Servicios" s on s.id = rb.servicio_id
        where reb.id = revision_estacion_id
            and public.user_is_org_admin(s.organizacion)
    )
);
commit;